import axios from "axios";
import { randomInt } from '../helpers'

const api = axios.create({
  baseURL: 'https://jsonplaceholder.typicode.com'
})

const carModels = [
  'Ford Mustang',
  'Honda Civic',
  'Chevorlet Corvette',
  'Honda Accord',
  'Toyota Camry',
  'Toyota Corolla',
  'Jeep Wrangler',
  'Jeep Cherokee',
  'Jeep Grand Cherokee',
  'Volkswagen Beetle',
  'Toyota Highlander',
  'Toyota 4Runner',
  'Subaru Outback',
  'Ford Model A',
  'Dodge Charger',
  'Ford F-Series',
  'Nissan Altima',
  'Mercedes-Benz C-Class',
  'Mercedes-Benz E-Class',
  'Honda CR-V',
  'Toyota Prius',
  'Ford Explorer',
  'Toyota Tundra',
  'Chevrolet Silverado',
  'Toyota Tacoma',
  'Audi A6',
  'Cadillac Escalade',
  'Lexus ES',
  'Chevrolet Malibu',
  'Toyota RAV4',
  'Ford Ranger',
  'Mercedes Benz GLE Class',
  'Toyota Land Cruiser',
  'Ford GT',
  'Volkswagen Vanagon',
  'Toyota Supra',
  'BMW M3',
  'Lexus LX',
  'Volkswagen Jetta',
  'BMW 4 Series',
  'Lexus GS',
  'Lexus IS',
  'Ford Fusion',
  'Mercedes Benz GLC Class',
  'Audi A4',
  'BMW 5 Series',
  'Subaru Legacy',
  'BMW 3 Series',
  'Cadillac CTS',
  'Lexus GX',
  'GMC Sierra',
  'Nissan Sentra',
  'Lexus RX',
  'Mazda 6',
  'Nissan Rogue',
  'Lexus SC',
  'BMW X5',
  'Audi A5',
  'Subaru Forester',
  'Audi A8',
  'Toyota Avalon',
  'Audi A7',
  'Jeep Renegade',
  'BMW 6 Series',
  'Audi S6',
  'Honda Pilot',
  'Acura MDX',
  'Ford Focus',
  'Hyundai Sonata',
  'Audi Q5',
  'Audi S4',
  'BMW 7 Series',
  'Ford Escape',
  'Cadillac XTS',
  'Tesla Model X',
  'Chevrolet Tahoe',
  'BMW X3',
  'Tesla Model S',
  'Audi R8',
  'Kia Optima',
  'Audi S5',
  'Hyundai Elantra',
  'Toyota Sequoia',
  'Kia Sportage',
  'Lexus CT',
  'Volkswagen New Beetle',
  'Lexus NX',
  'GMC Terrain',
  'Chevrolet / GMC C/K',
  'Chevrolet Equinox',
  'Acura Legend',
  'Chevrolet Monte Carlo',
  'Dodge Durango',
  'Honda Odyssey',
  'Cadillac SRX',
  'Audi Q7',
  'Audi Quattro',
  'Audi A3',
  'Audi Q3',
  'BMW M5',
  'Tesla Model 3',
  'Cadillac ATS',
  'BMW 8 Series',
  'Hyundai Tucson',
  'Kia Sorento',
  'Audi RS 6',
  'Dodge Caravan',
  'Ford Edge',
  'Chevrolet Colorado',
  'Cadillac STS',
  'Toyota Celica',
  'Tesla Roadster',
  'Audi S7',
  'Mazda 3',
  'Honda HR-V',
  'BMW 335',
  'Lincoln MKZ',
  'Cadillac XT5',
  'Volkswagen Golf',
  'Chevrolet Nova',
  'Lincoln MKX',
  'Mitsubishi Outlander',
  'Chevrolet Traverse',
  'Volkswagen Passat',
  'Subaru BRZ',
  'Infiniti QX60',
  'Lexus HS',
  'Mazda CX-5',
  'Subaru XV Crosstrek',
  'Acura RSX',
  'Honda Prelude',
  'Lexus LFA',
  'BMW X1',
  'Hyundai Genesis',
  'Lexus RC',
  'GMC Acadia',
  'Acura ILX',
  'Lexus NX 200t',
  'Cadillac XLR',
  'Cadillac Seville',
  'Toyota Corona',
  'Toyota C-HR',
  'Acura TLX',
  'Toyota Sienna',
  'Acura TL',
  'Nissan Titan',
  'Subaru Impreza',
  'Volkswagen Tiguan',
  'Buick Enclave',
  'Acura RDX',
  'Chevrolet 210',
  'Volkswagen Rabbit',
  'Chevrolet S10',
  'Chrysler 300',
  'Buick Encore',
  'Volkswagon GTI',
  'Chevrolet Cruze',
  'Volvo 200 series',
  'Audi RS 4',
  'Hyundai Santa Fe',
  'Mazda CX-9',
  'Toyota Solara',
  'Audi Cabriolet',
  'Hudson',
  'Kia Soul',
  'Acura NSX',
  'Honda Ridgeline',
  'Infiniti Q50',
  'Alfa Romeo Giulia',
  'BMW E38',
  'Honda S2000',
  'Honda Fit',
  'Chevrolet Avalanche',
  'Honda Passport',
  'Honda Insight',
  'Infiniti EX series',
  'Toyota FJ Cruiser',
  'Kia Forte',
  'Toyota MR2',
  'Subaru XT',
  'Kia Sedona',
  'Hudson Hornet',
  'Chrysler Pacifica',
  'Toyota T100',
  'Subaru SVX',
  'Volvo 900 Series',
  'Volkswagen Touareg',
  'Subaru L Series',
  'Volkswagen GLI',
  'Volkswagen CC',
  'Nissan Frontier',
  'Volkswagen Scirocco',
  'Toyota Venza',
  'Subaru WRX',
  'Honda Element',
  'Subaru Baja',
  'Acura ZDX',
  'Buick Envision',
  'Chevrolet Master',
  'Acura TSX',
  'Ford Flex',
  'Chevrolet Lumina',
  'Chevrolet SSR',
  'Toyota Tercel',
  'Volvo 850',
  'Volkswagen Eos',
  'Toyota Cressida',
  'Dodge Journey',
  'Ford LTD',
  'Volkswagen Routan',
  'Hyundai Excel',
  'GMC Canyon',
  'Volkswagen Cabriolet / Cabrio',
  'Subaru Loyale',
  'Acura SLX',
  'Volvo 700 series',
  'Acura RL',
  'Subaru Tribeca',
  'Volkswagen Corrado',
  'Volkswagen Phaeton',
  'Hyundai Ioniq',
  'Hyundai Tiburon',
  'Ford Transit Connect',
  'Toyota Matrix',
  'Toyota Yaris',
  'Ford Focus C-Max',
  'Toyota Previa',
  'Hyundai Genesis Coupe',
  'Hyundai Entourage',
  'Volkswagen R32',
  'Chevrolet Lumina APV',
  'Hyundai Veloster',
  'Acura Vigor',
  'Hyundai Veracruz',
  'Chevrolet Aveo',
  'Ford Granada',
  'Chevrolet LUV',
  'Toyota Starlet',
  'Hyundai Equus',
  'Chevrolet Kodiak',
  'Ford Five Hundred',
  'Volkswagen Fox',
  'Ford Freestyle',
  'Toyota Echo',
  'Chevrolet Astro',
  'Toyota Paseo',
  'Ford Freestar',
  'Subaru Brat',
  'Hyundai XG300',
  'Volkswagen Quantum',
  'Volkswagen Eurovan',
  'Hyundai Scoupe',
  'Suzuki Esteem',
  'Subaru Justy',
  'Toyota Raum',
  'Chevrolet Metro',
  'Volkswagen Dasher',
  'Suzuki Aerio',
  'Suzuki Equator'
];

export const fetchUserData = async formData => {
  // TODO: Currently using mock data

  const userId = randomInt(1, 10)
  const carModelIx = randomInt(1, 10)
  const carYear = randomInt(2018, (new Date()).getFullYear());

  const user = await api.get('/users/' + userId);

  return {
    ...user.data,
    vehicle: {
      car: {
        model: carModels[carModelIx],
        year: carYear
      }
    }
  }
}