export const START_FETCH_COBERTURAS_LIST = 'START_FETCH_COBERTURAS_LIST';
export const FINISH_FETCH_COBERTURAS_LIST = 'FINISH_FETCH_COBERTURAS_LIST';

export const START_FETCH_COBERTURAS_DATA = 'START_FETCH_COBERTURAS_DATA';
export const FINISH_FETCH_COBERTURAS_DATA = 'FINISH_FETCH_COBERTURAS_DATA';
